name: Leetcode-Solution-Collectinator

on:
  schedule:
  - cron: '5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./work/


    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: setting-up the env variables
        run: |
          touch .env
          echo COOKIE_SECRET=${{secrets.COOKIE_SECRET}} >> .env
      # Runs a single command using the runners shell
      - name: Run the downloader script
        run: |
          npm install --save
          node ~/work/.github/src/app.js
      - name: pushing the changes!!
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply commit
