name: Leetcode-Solution-Collectinator

on:
  schedule:
  - cron: '5 * * * *'

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .github/workflows/src
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
  
      - name: installing npm
        run: |
          npm install -g npm 
      # Runs a single command using the runners shell
      - name: Run the downloader script
        run: |
          npm install --save
          node app.js
        env : 
          COOKIE_SECRET: ${{secrets.COOKIE_SECRET}} 
      - name: pushing the changes!!
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply commit
